/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2026-03-31 02:02:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;

public final class MemberJoinProc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");
 
		request.setCharacterEncoding("UTF-8");	
	
		//취미 부분은 별도로 읽어드려 다시 빈클래스에 저장 
		String [] hobby = request.getParameterValues("hobby");
		
		//배열에 있는 내용알을 하나의 스트링으로 저장 
		String texthobby="";
		
		for(int i = 0 ;i < hobby.length; i++){
			texthobby += hobby[i]+" ";
		}
	
      out.write("\n");
      out.write("\t\n");
      out.write("\t<!--useBean을 이용하여 한꺼번에 데이터를 받아옴  -->\n");
      out.write("\t");
      bean.MemberBean mbean = null;
      mbean = (bean.MemberBean) _jspx_page_context.getAttribute("mbean", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mbean == null){
        mbean = new bean.MemberBean();
        _jspx_page_context.setAttribute("mbean", mbean, javax.servlet.jsp.PageContext.PAGE_SCOPE);
        out.write('\n');
        out.write('	');
        out.write('	');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("mbean"), request);
        out.write("<!--맵핑 시키시오  -->\n");
        out.write("\t");
      }
      out.write('\n');
      out.write('\n');
      out.write('	');
 
	    mbean.setHobby(texthobby); //기존의 취미는 주소 번지가 저장되기에  위에 배열의 내용을 하나의 스트림으로 저장한 변수를 다시 입력 
	   
	    String dbID = "admin";
	    String dbPassword = "testtest";
	    String dbURL = "jdbc:postgresql://localhost:5432/jsp_clone";
	
	    try{
	   		
	    	Class.forName("org.postgresql.Driver");
	   	
	   		//2.해당 데이터 베이스에 접속
	   		Connection conn = DriverManager.getConnection(dbURL, dbID, dbPassword);
		    
	   		//3. 접속후 쿼리 준비하여 쿼리를 실행하여 쿼리를 사용하도록 설정 
	   		 String SQL = "INSERT INTO member (id, pass1, email, tel, hobby, job, age, info) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
	   		
	   		//쿼리를 사용하도록 설정 
			PreparedStatement pstmt = conn.prepareStatement(SQL);//jsp에서 쿼리를 사용하도록 설정
			
	   		//?에 맞게 데이터를 맵핑
	   		pstmt.setString(1,mbean.getId());
	   		pstmt.setString(2,mbean.getPass1());
	   		pstmt.setString(3,mbean.getEmail());
	   		pstmt.setString(4,mbean.getTel());
	   		pstmt.setString(5,mbean.getHobby());
	   		pstmt.setString(6,mbean.getJob());
	   		pstmt.setString(7,mbean.getAge());
	   		pstmt.setString(8,mbean.getInfo());
	   		
	   		//4.오라클에서 퀴리를 실행 하시오 
	   		pstmt.executeUpdate();//insert,update,delete 시 사용하는 메소드 
	   		
	   		//5.자원 반납 
	   		conn.close();
	   		
	   		
	    }catch(Exception e){
	    	e.printStackTrace();
	   	}
	
	
	
      out.write("\n");
      out.write("    \t ~~postgreSQL 접속 완료\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
