version: "3.8"
services:
  db:
    image: postgres:15
    container_name: jsp-clone-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: testtest
      POSTGRES_DB: jsp_clone
    volumes:
      - jsp_db_data:/var/lib/postgresql/data

volumes:
  jsp_db_data:
